### ISSUE TITLE
CentOS7.2 installation failing

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-setup#92]
Error: 
```
[root@localhost ~]# /sbin/gluu-serverd-2.4.1 start
Job for systemd-nspawn@gluu-server-2.4.1.service failed because the control process exited with error code. See "systemctl status systemd-nspawn@gluu-server-2.4.1.service" and "journalctl -xe" for details.
```

CentOS version: 
```
[root@localhost ~]# cat /etc/*-release
CentOS Linux release 7.2.1511 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.2.1511 (Core)
CentOS Linux release 7.2.1511 (Core)
```

**Comment by mzico** [comment]
@nynymike , @adrian-gluu , @yurem: Do you think we should change the container name? Seems like  systemd-nspaw has some issues with naming in CentOS7.2? 

[https://github.com/systemd/systemd/issues/1307](This) has some similarity with what we are getting for CentOS7.2

Stack trace: 

`[root@zico ~]# /sbin/gluu-serverd-2.4.1 status
● systemd-nspawn@gluu-server-2.4.1.service - Container gluu/server/2.4.1
   Loaded: loaded (/usr/lib/systemd/system/systemd-nspawn@.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sun 2016-02-28 10:08:35 EST; 5min ago
     Docs: man:systemd-nspawn(1)
  Process: 9068 ExecStart=/usr/bin/systemd-nspawn --quiet --keep-unit --boot --link-journal=try-guest --network-veth --machine=%I (code=exited, status=1/FAILURE)
 Main PID: 9068 (code=exited, status=1/FAILURE)
   Status: "Terminating..."

Feb 28 10:08:35 zico.gluu.org systemd[1]: Starting Container gluu/server/2.4.1...
Feb 28 10:08:35 zico.gluu.org systemd-nspawn[9068]: Invalid machine name: gluu/server/2.4.1
Feb 28 10:08:35 zico.gluu.org systemd[1]: systemd-nspawn@gluu-server-2.4.1.service: main process exited, code=exited, status=1/FAILURE
Feb 28 10:08:35 zico.gluu.org systemd[1]: Failed to start Container gluu/server/2.4.1.
Feb 28 10:08:35 zico.gluu.org systemd[1]: Unit systemd-nspawn@gluu-server-2.4.1.service entered failed state.
Feb 28 10:08:35 zico.gluu.org systemd[1]: systemd-nspawn@gluu-server-2.4.1.service failed.`

**Comment by mzico** [comment]
@aveekbu: I think we can test with 2.4.2 now as it's released.

**Comment by aveekbu** [comment]
We are still facing the issue on new GluuCE 2.4.2. Here's my testing result goes,
```
[root@aveek yum.repos.d]# cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 

[root@aveek yum.repos.d]# /sbin/gluu-serverd-2.4.2 start
Job for systemd-nspawn@gluu-server-2.4.2.service failed because the control process exited with error code. See "systemctl status systemd-nspawn@gluu-server-2.4.2.service" and "journalctl -xe" for details.
[root@aveek yum.repos.d]# systemctl status systemd-nspawn@gluu-server-2.4.2.service
● systemd-nspawn@gluu-server-2.4.2.service - Container gluu/server/2.4.2
   Loaded: loaded (/usr/lib/systemd/system/systemd-nspawn@.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2016-03-02 14:13:07 EST; 29s ago
     Docs: man:systemd-nspawn(1)
  Process: 23633 ExecStart=/usr/bin/systemd-nspawn --quiet --keep-unit --boot --link-journal=try-guest --network-veth --machine=%I (code=exited, status=1/FAILURE)
 Main PID: 23633 (code=exited, status=1/FAILURE)
   Status: "Terminating..."

Mar 02 14:13:07 aveek.gluu.org systemd[1]: Starting Container gluu/server/2.4.2...
Mar 02 14:13:07 aveek.gluu.org systemd-nspawn[23633]: Invalid machine name: gluu/server/2.4.2
Mar 02 14:13:07 aveek.gluu.org systemd[1]: systemd-nspawn@gluu-server-2.4.2.service: main process exited, code=exited, status=1/FAILURE
Mar 02 14:13:07 aveek.gluu.org systemd[1]: Failed to start Container gluu/server/2.4.2.
Mar 02 14:13:07 aveek.gluu.org systemd[1]: Unit systemd-nspawn@gluu-server-2.4.2.service entered failed state.
Mar 02 14:13:07 aveek.gluu.org systemd[1]: systemd-nspawn@gluu-server-2.4.2.service failed.
[root@aveek yum.repos.d]# rpm -qa |grep gluu
gluu-server-2.4.2-1-1.centos7.x86_64
```

**Comment by mzico** [comment]
@adrian-gluu : 

Tried with `http://repo.gluu.org/centos/7/gluu-server-2.4.2-1-1.centos7.x86_64.rpm`. 

Problems: 

1. Problem with iptables: 

    [root@gluu_server_2 certs]# /bin/systemctl status  iptables.service
    ● iptables.service
    Loaded: not-found (Reason: No such file or directory)
    Active: inactive (dead)
    [root@gluu_server_2 certs]# /bin/systemctl start iptables.service
    Failed to start iptables.service: Unit iptables.service failed to load: No such file or directory.
    [root@gluu_server_2 certs]#

2. Problem with JKS creation: 

   00:34:20 03/06/16 Creating keystore shibIDP
   00:34:20 03/06/16 Running: /usr/bin/openssl pkcs12 -export -inkey /etc/certs/shibIDP.key -in   /etc/certs/shibIDP.crt -out /etc/certs/shibIDP.pkcs12 -name rpmtesting.gluu.org -passout pass:p78mY6Qdznfk
   00:34:20 03/06/16 Running: /usr/java/latest/bin/keytool -importkeystore -srckeystore /etc/certs/shibIDP.pkcs12 -srcstorepass p78mY6Qdznfk -srcstoretype PKCS12 -destkeystore /etc/certs/shibIDP.jks -deststorepass p78mY6Qdznfk -deststoretype JKS -keyalg RSA -noprompt
   00:34:20 03/06/16 Error running command : /usr/java/latest/bin/keytool -importkeystore -srckeystore /etc/certs/shibIDP.pkcs12 -srcstorepass p78mY6Qdznfk -srcstoretype PKCS12 -destkeystore /etc/certs/shibIDP.jks -deststorepass p78mY6Qdznfk -deststoretype JKS -keyalg RSA -noprompt
   00:34:20 03/06/16 Traceback (most recent call last):
  File "./setup.py", line 1495, in run
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=cwd)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

  00:34:20 03/06/16 Running: /bin/chown tomcat:tomcat /etc/certs/shibIDP.pkcs12
  00:34:20 03/06/16 Running: /bin/chmod 700 /etc/certs/shibIDP.pkcs12
  00:34:20 03/06/16 Running: /bin/chown tomcat:tomcat /etc/certs/shibIDP.jks
  00:34:20 03/06/16 /bin/chown: cannot access ‘/etc/certs/shibIDP.jks’: No such file or directory

  00:34:20 03/06/16 Running: /bin/chmod 700 /etc/certs/shibIDP.jks
  00:34:20 03/06/16 /bin/chmod: cannot access ‘/etc/certs/shibIDP.jks’: No such file or directory

3. OpenID key creation failing: 


  00:34:20 03/06/16 Writing oxAuth OpenID Connect keys
  00:34:20 03/06/16 Failed to write oxAuth OpenID Connect key to /etc/certs/oxauth-web-keys.json
  00:34:20 03/06/16 Loading file ./output/oxauth-config.json
  00:34:20 03/06/16 Loading file ./output/oxauth-static-conf.json
  00:34:20 03/06/16 Loading file ./static/oxauth/oxauth-errors.json
  00:34:20 03/06/16 Loading file /etc/certs/oxauth-web-keys.json
  00:34:20 03/06/16 Error loading file
  00:34:20 03/06/16 Traceback (most recent call last):
  File "./setup.py", line 1463, in generate_base64_file
    plain_file = open(fn)
  IOError: [Errno 2] No such file or directory: '/etc/certs/oxauth-web-keys.json'

  00:34:20 03/06/16 ***** Error caught in main loop *****
  00:34:20 03/06/16 Traceback (most recent call last):
  File "./setup.py", line 1817, in <module>
    installObject.generate_base64_configuration()
  File "./setup.py", line 1483, in generate_base64_configuration
    self.oxauth_openid_key_base64 = self.generate_base64_ldap_file(self.oxauth_openid_key_json)
  File "./setup.py", line 1477, in generate_base64_ldap_file
    return self.generate_base64_file(fn, 1)
  File "./setup.py", line 1472, in generate_base64_file
    plain_file_b64encoded_text = self.reindent(plain_file_b64encoded_text, num_spaces)
  File "./setup.py", line 1453, in reindent
    text = string.split(text, '\n')
  File "/usr/lib64/python2.7/string.py", line 292, in split
    return s.split(sep, maxsplit)
  AttributeError: 'NoneType' object has no attribute 'split'

**Comment by zamilskhan** [comment]
@adrian-gluu:

```
13:19:22 03/07/16 bash: /usr/java/latest/bin/java: No such file or directory

13:19:22 03/07/16 bash: /usr/java/latest/bin/java: No such file or directory

```
```
13:19:24 03/07/16 Error running command : /usr/java/latest/bin/keytool -importkeystore -srckeystore /etc/certs/shibIDP.pkcs12 -srcstorepass MtPll0E5lQSu -srcstoretype PKCS12 -destkeystore /etc/certs/shibIDP.jks -deststorepass MtPll0E5lQSu -deststoretype JKS -keyalg RSA -noprompt
13:19:24 03/07/16 Traceback (most recent call last):
  File "./setup.py", line 1495, in run
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=cwd)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

13:19:24 03/07/16 /bin/chown: cannot access ‘/etc/certs/shibIDP.jks’: No such file or directory

13:19:24 03/07/16 /bin/chmod: cannot access ‘/etc/certs/shibIDP.jks’: No such file or directory

13:19:24 03/07/16 Error running command : /usr/java/latest/bin/keytool -importkeystore -srckeystore /etc/certs/asimba.pkcs12 -srcstorepass Lm7gOWBwznYR -srcstoretype PKCS12 -destkeystore /etc/certs/asimbaIDP.jks -deststorepass Lm7gOWBwznYR -deststoretype JKS -keyalg RSA -noprompt
13:19:24 03/07/16 Traceback (most recent call last):
  File "./setup.py", line 1495, in run
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=cwd)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

13:19:24 03/07/16 /bin/chown: cannot access ‘/etc/certs/asimbaIDP.jks’: No such file or directory

13:19:24 03/07/16 /bin/chmod: cannot access ‘/etc/certs/asimbaIDP.jks’: No such file or directory

13:19:24 03/07/16 bash: /usr/java/latest/bin/java: No such file or directory

13:19:24 03/07/16 Error loading file
13:19:24 03/07/16 Traceback (most recent call last):
  File "./setup.py", line 1463, in generate_base64_file
    plain_file = open(fn)
IOError: [Errno 2] No such file or directory: '/etc/certs/oxauth-web-keys.json'

13:19:24 03/07/16 ***** Error caught in main loop *****
13:19:24 03/07/16 Traceback (most recent call last):
  File "./setup.py", line 1817, in <module>
    installObject.generate_base64_configuration()
  File "./setup.py", line 1483, in generate_base64_configuration
    self.oxauth_openid_key_base64 = self.generate_base64_ldap_file(self.oxauth_openid_key_json)
  File "./setup.py", line 1477, in generate_base64_ldap_file
    return self.generate_base64_file(fn, 1)
  File "./setup.py", line 1472, in generate_base64_file
    plain_file_b64encoded_text = self.reindent(plain_file_b64encoded_text, num_spaces)
  File "./setup.py", line 1453, in reindent
    text = string.split(text, '\n')
  File "/usr/lib64/python2.7/string.py", line 292, in split
    return s.split(sep, maxsplit)
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by adrian-gluu** [comment]
can you guys test this one:
http://repo.gluu.org/centos/7/gluu-server-2.4.2-1-3.centos7.x86_64.rpm

**Comment by zamilskhan** [comment]
This works, installation and GUI

**Comment by adrian-gluu** [comment]
ok if this works on 7.2 i will use the same technique to build rhel7 pkg

**Comment by adrian-gluu** [comment]
can you guys test RHEL7 pkg?
http://repo.gluu.org/rhel/7/gluu-server-2.4.2-1-2.rhel7.x86_64.rpm

**Comment by gk1github** [comment]
Guys today I installed Gluu on Centos, these 2 work together !!
CentOS Linux release 7.2.1511 (Core)
gluu-server-2.4.2-1-3.centos7.x86_64.rpm

**Comment by mzico** [comment]
@gk1github thanks for confirmation.
